# Generated by Django 3.2.15 on 2022-09-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='tvshow',
            name='birthDay',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='network',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
