# Generated by Django 3.2.15 on 2022-09-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20220905_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='likedby',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='likes',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
    ]
